name: CI-CD
on:
  workflow_dispatch:
  push:
    branches:
    - feature/*
    - develop
    - release/*
    - hotfix/*
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
    - develop
    
jobs:        
  test_actor:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[skip-ci]') && github.actor != 'gitbot'"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.EDGARPAT }}
      - name: actor
        run: |
          echo "actor is: ${GITHUB_ACTOR}"
      - name: echoing
        run: |
          echo "$(date)" > VERSION
          git config --local user.email "gitbot@github.com"
          git config --local user.name "gitbot"
          git commit -m "update version files" -a
          git push
