name: CI-CD
on:
  workflow_dispatch:
  push:
    branches:
    - feature/*
    - develop
    - release/*
    - hotfix/*
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
    - develop

jobs:
  get_actor:
    runs-on: ubuntu-latest
    outputs:
      actor: ${{ steps.actor.outputs.actor }}
    steps:
      - uses: actions/checkout@v2
      - name: actor
        run: |
          ACTOR=$(git log -1 --pretty=format:'%an')
          echo "$ACTOR"
          echo "actor=$ACTOR" >> $GITHUB_OUTPUT

  test_actor:
    runs-on: ubuntu-latest
    needs: [get_actor]
    if: "!contains(github.event.commits[0].message, '[skip-ci]') && needs.get_actor.outputs.actor != 'gitbot'"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.EDGARPAT }}
      - name: actor
        run: |
          echo "actor is: ${{needs.get_actor.outputs.actor}}"
      - name: echoing
        run: |
          echo "$(date)" > VERSION
          git config --local user.email "gitbot@github.com"
          git config --local user.name "gitbot"
          git commit -m "update version files" -a
          git push
