name: CI-CD
on:
  workflow_dispatch:
  push:
    branches:
    - feature/*
    - develop
    - release/*
    - hotfix/*
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
    - develop
env:
  SKIP_CI_MESSAGE: '[skip-ci]'
  SKIP_CI_ACTOR: 'gitbot'
jobs:
  get_actor:
    runs-on: ubuntu-latest
    outputs:
      actor: ${{ steps.actor.outputs.actor }}
    steps:
      - uses: actions/checkout@v2
      - name: actor
        id: actor
        run: |
          ACTOR=$(git log -1 --pretty=format:'%an')
          echo "$ACTOR"
          echo "actor=$ACTOR" >> $GITHUB_OUTPUT

  test_actor:
    runs-on: ubuntu-latest
    needs: [get_actor]
    if: ${{ !(contains(github.event.commits[0].message, env.SKIP_CI_MESSAGE) && needs.get_actor.outputs.actor != env.SKIP_CI_ACTOR }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.EDGARPAT }}
      - name: actor
        run: |
          echo "actor to ignore is: $SKIP_CI_ACTOR"
          echo "actor is: ${{needs.get_actor.outputs.actor}}"
      - name: echoing
        run: |
          echo "$(date)" > VERSION
          git config --local user.email "gitbot@github.com"
          git config --local user.name "$SKIP_CI_ACTOR"
          git commit -m "update version files" -a
          git push
