name: CI-CD
on:
  workflow_dispatch:
  push:
    branches:
    - feature/*
    - develop
    - release/*
    - hotfix/*
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
    - develop
env:
  SKIP_CI_MESSAGE: '[skip-ci]'
  SKIP_CI_ACTOR: 'gitbot'
jobs:
  prepare_envs:
    runs-on: ubuntu-latest
    outputs:
      actual_actor: ${{ steps.get_envs.outputs.actual_actor }}
      skip_ci_message: ${{ steps.get_envs.outputs.skip_ci_message }}
      skip_ci_actor: ${{ steps.get_envs.outputs.skip_ci_actor }}
    steps:
      - uses: actions/checkout@v2
      - name: get_envs
        id: get_envs
        run: |
          ACTUAL_ACTOR=$(git log -1 --pretty=format:'%an')
          echo "$ACTUAL_ACTOR"
          echo "$SKIP_CI_MESSAGE"
          echo "$SKIP_CI_ACTOR"
          echo "actual_actor=$ACTUAL_ACTOR" >> $GITHUB_OUTPUT
          echo "skip_ci_message=$SKIP_CI_MESSAGE" >> $GITHUB_OUTPUT
          echo "skip_ci_actor=$SKIP_CI_ACTOR" >> $GITHUB_OUTPUT

  test_actor:
    runs-on: ubuntu-latest
    needs: [prepare_envs]
    if: "!(contains(github.event.commits[0].message, needs.prepare_envs.outputs.skip_ci_message) || needs.prepare_envs.outputs.skip_ci_actor == needs.prepare_envs.outputs.actual_actor)"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.EDGARPAT }}
      - name: actor
        run: |
          echo "actor to ignore is: $SKIP_CI_ACTOR"
          echo "actor is: ${{needs.prepare_envs.outputs.actor}}"
      - name: echoing
        run: |
          echo "$(date)" > VERSION
          git config --local user.email "gitbot@github.com"
          git config --local user.name "$SKIP_CI_ACTOR"
          git commit -m "update version files" -a
          git push
